/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/parceiro`; params?: Router.UnknownInputParams; } | { pathname: `/registar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explorar` | `/explorar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | { pathname: `/explorar/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/parceiro`; params?: Router.UnknownOutputParams; } | { pathname: `/registar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explorar` | `/explorar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownOutputParams; } | { pathname: `/explorar/[slug]`, params: Router.UnknownOutputParams & { slug: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/parceiro${`?${string}` | `#${string}` | ''}` | `/registar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/conta${`?${string}` | `#${string}` | ''}` | `/conta${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explorar${`?${string}` | `#${string}` | ''}` | `/explorar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mapa${`?${string}` | `#${string}` | ''}` | `/mapa${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/parceiro`; params?: Router.UnknownInputParams; } | { pathname: `/registar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/conta` | `/conta`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explorar` | `/explorar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mapa` | `/mapa`; params?: Router.UnknownInputParams; } | `/explorar/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/explorar/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } };
    }
  }
}
